version: '3'
services:
  # api 镜像需要更新
  yzbhl:
    image: ew_yzbhl_image
    build: .
    container_name: ew_yzbhl_container
    ports:
      - 3000:3000
    restart: always

  # nginx 镜像不需要更新
  nginx:
    image: yzbhl_nginx
    build: ./.nginx
    container_name: yzbhl_nginx_container
    ports:
      - 3214:80/tcp
      # - 3215:443/tcp
    restart: always
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
      # - ./.nginx/cert:/etc/nginx/cert
    depends_on:
      - yzbhl

