version: '3'
services:
  # api 镜像需要更新
  yzbhl-container:
    image: yzbhl-container
    build: .
    container_name: yzbhl_container
    ports:
      - 3000:3000
    command: ["pm2-runtime", "start", "ecosystem.config.cjs"]
    restart: always

  # nginx 镜像不需要更新
  yzbhl-nginx-container:
    image: nginx:latest
    container_name: yzbhl_nginx_container
    ports:
      - 80:80/tcp
      # - 3215:443/tcp
    restart: always
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
      # - ./.nginx/cert:/etc/nginx/cert
    depends_on:
      - yzbhl-container
